on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: 0

name: Android Integration
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.11' # Изолированная рабочая версия

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Linux Packages
      # Используем родной python3 системы для apt, ошибок не будет
      run: |
        sudo apt update
        sudo apt -y install automake libltdl-dev libffi-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libsqlite3-dev tk-dev libgdbm-compat-dev

    - name: Install Buildozer and dependencies
      # Ставим всё строго внутри изолированного Python 3.11
      run: |
        /opt/hostedtoolcache/Python/3.11.11/x64/bin/python -m pip install --upgrade pip
        /opt/hostedtoolcache/Python/3.11.11/x64/bin/python -m pip install buildozer cython

    - name: Pre-install Android SDK Tools
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$PATH
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true
        sdkmanager --install "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Debug Build APK
      run: |
        sudo chown -R runner:runner /home/runner/.buildozer
        export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
        
        # Запускаем сборщик напрямую через бинарник Python 3.11
        /opt/hostedtoolcache/Python/3.11.11/x64/bin/buildozer android debug
