on:
  push:
    branches: [ "**" ]
  workflow_dispatch: # Добавлена кнопка ручного запуска!

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: 0

name: Android Integration
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython git+https://github.com/kivy/buildozer.git

    - name: Install Linux Packages
      run: |
        sudo apt update
        sudo apt -y install automake libltdl-dev libffi-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libsqlite3-dev tk-dev libgdbm-compat-dev

    - name: Pre-install Android SDK Tools
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$PATH
        
        # Заставляем систему принять абсолютно все лицензии, включая новые
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true
        
        # Принудительно устанавливаем конкретную стабильную версию build-tools
        sdkmanager --install "build-tools;34.0.0" "platform-tools" "platforms;android-34"
        
        # Делаем симлинк, чтобы Buildozer гарантированно увидел утилиту aidl
        sudo mkdir -p /home/runner/.buildozer/android/platform/android-sdk/build-tools
        sudo ln -s $ANDROID_HOME/build-tools/34.0.0 /home/runner/.buildozer/android/platform/android-sdk/build-tools/34.0.0



    - name: Debug Build APK
      run: |
        sudo chown -R runner:runner /home/runner/.buildozer
        
        # Обманываем устаревший Buildozer: создаем старый путь и связываем его с новым sdkmanager
        sudo mkdir -p /usr/local/lib/android/sdk/tools/bin
        sudo ln -sf /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager /usr/local/lib/android/sdk/tools/bin/sdkmanager
        
        export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
        buildozer android debug







    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kivy-App-APK
        path: bin/*.apk
