on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: 0

name: Android Integration
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.11 (FORCE)
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.11' # Жестко фиксируем рабочую версию для сервера

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Link host python to 3.11
      run: |
        # Этот хак подменяет глобальный вызов 'python3' на сервере на нашу версию 3.11
        sudo ln -sf /opt/hostedtoolcache/Python/3.11.11/x64/bin/python3 /usr/local/bin/python3
        sudo ln -sf /opt/hostedtoolcache/Python/3.11.11/x64/bin/python3 /usr/bin/python3
        python3 --version # В логах должно напечататься 3.11!

    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer cython git+https://github.com

    - name: Install Linux Packages
      run: |
        sudo apt update
        sudo apt -y install automake libltdl-dev libffi-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libsqlite3-dev tk-dev libgdbm-compat-dev

    - name: Pre-install Android SDK Tools
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$PATH
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true
        sdkmanager --install "build-tools;34.0.0" "platform-tools" "platforms;android-34"

    - name: Debug Build APK
      run: |
        sudo chown -R runner:runner /home/runner/.buildozer
        export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
        buildozer android debug
